-- MySQL Script generated by MySQL Workbench
-- Fri Jul 21 10:13:14 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Asignacion_1
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Asignacion_1` ;

-- -----------------------------------------------------
-- Schema Asignacion_1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Asignacion_1` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema libros
-- -----------------------------------------------------
USE `Asignacion_1` ;

-- -----------------------------------------------------
-- Table `Asignacion_1`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Asignacion_1`.`users` ;

CREATE TABLE IF NOT EXISTS `Asignacion_1`.`users` (
  `id` INT UNSIGNED NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `first_name_UNIQUE` (`first_name` ASC) VISIBLE,
  UNIQUE INDEX `last_name_UNIQUE` (`last_name` ASC) VISIBLE,
  UNIQUE INDEX `created_at_UNIQUE` (`created_at` ASC) VISIBLE,
  UNIQUE INDEX `updated_at_UNIQUE` (`updated_at` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Asignacion_1`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Asignacion_1`.`users` ;

CREATE TABLE IF NOT EXISTS `Asignacion_1`.`users` (
  `id` INT UNSIGNED NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `first_name_UNIQUE` (`first_name` ASC) VISIBLE,
  UNIQUE INDEX `last_name_UNIQUE` (`last_name` ASC) VISIBLE,
  UNIQUE INDEX `created_at_UNIQUE` (`created_at` ASC) VISIBLE,
  UNIQUE INDEX `updated_at_UNIQUE` (`updated_at` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Asignacion_1`.`books`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Asignacion_1`.`books` ;

CREATE TABLE IF NOT EXISTS `Asignacion_1`.`books` (
  `id_books` INT UNSIGNED NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `num_of_pages` INT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id_books`),
  UNIQUE INDEX `id_books_UNIQUE` (`id_books` ASC) VISIBLE,
  UNIQUE INDEX `num_of_pages_UNIQUE` (`num_of_pages` ASC) VISIBLE,
  UNIQUE INDEX `title_UNIQUE` (`title` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Asignacion_1`.`favorites`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Asignacion_1`.`favorites` ;

CREATE TABLE IF NOT EXISTS `Asignacion_1`.`favorites` (
  `users_id` INT UNSIGNED NOT NULL,
  `books_id_books` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`users_id`, `books_id_books`),
  INDEX `fk_users_has_books_books1_idx` (`books_id_books` ASC) VISIBLE,
  INDEX `fk_users_has_books_users_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_has_books_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `Asignacion_1`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_books_books1`
    FOREIGN KEY (`books_id_books`)
    REFERENCES `Asignacion_1`.`books` (`id_books`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
