-- MySQL Script generated by MySQL Workbench
-- Tue Jun 20 09:30:40 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dojo_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `dojo_db` ;

-- -----------------------------------------------------
-- Schema dojo_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dojo_db` DEFAULT CHARACTER SET utf8 ;
USE `dojo_db` ;

-- -----------------------------------------------------
-- Table `dojo_db`.`productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dojo_db`.`productos` ;

CREATE TABLE IF NOT EXISTS `dojo_db`.`productos` (
  `id_producto` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `precio` INT NULL,
  PRIMARY KEY (`id_producto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dojo_db`.`categorias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dojo_db`.`categorias` ;

CREATE TABLE IF NOT EXISTS `dojo_db`.`categorias` (
  `id_categorias` INT NOT NULL AUTO_INCREMENT,
  `nombre_categoria` VARCHAR(45) NULL,
  `productos_id_producto` INT NOT NULL,
  PRIMARY KEY (`id_categorias`),
  INDEX `fk_categorias_productos_idx` (`productos_id_producto` ASC) VISIBLE,
  CONSTRAINT `fk_categorias_productos`
    FOREIGN KEY (`productos_id_producto`)
    REFERENCES `dojo_db`.`productos` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
