-- MySQL Script generated by MySQL Workbench
-- Tue Jul 25 08:29:35 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Asignacion_1
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Asignacion_1` ;

-- -----------------------------------------------------
-- Schema Asignacion_1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Asignacion_1` DEFAULT CHARACTER SET utf8 ;
USE `Asignacion_1` ;

-- -----------------------------------------------------
-- Table `Asignacion_1`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Asignacion_1`.`users` ;

CREATE TABLE IF NOT EXISTS `Asignacion_1`.`users` (
    `id_users` INT NOT NULL AUTO_INCREMENT,
    `first_name` VARCHAR(45) NOT NULL,
    `last_name` VARCHAR(45) NOT NULL,
    `created_at` DATETIME NOT NULL,
    `updated_at` DATETIME NOT NULL,
    PRIMARY KEY (`id_users`),
    UNIQUE INDEX `id_users_UNIQUE` (`id_users` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Asignacion_1`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Asignacion_1`.`users` ;

CREATE TABLE IF NOT EXISTS `Asignacion_1`.`users` (
    `id_users` INT NOT NULL AUTO_INCREMENT,
    `first_name` VARCHAR(45) NOT NULL,
    `last_name` VARCHAR(45) NOT NULL,
    `created_at` DATETIME NOT NULL,
    `updated_at` DATETIME NOT NULL,
    PRIMARY KEY (`id_users`),
    UNIQUE INDEX `id_users_UNIQUE` (`id_users` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Asignacion_1`.`friendships`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Asignacion_1`.`friendships` ;

CREATE TABLE IF NOT EXISTS `Asignacion_1`.`friendships` (
    `id_friendships` INT NOT NULL AUTO_INCREMENT,
    `creted_at` DATETIME NOT NULL,
    `updated_at` DATETIME NOT NULL,
    `users_id_users` INT NOT NULL,
    `users_id_users1` INT NOT NULL,
    PRIMARY KEY (`id_friendships`),
    UNIQUE INDEX `id_friendships_UNIQUE` (`id_friendships` ASC) VISIBLE,
    INDEX `fk_friendships_users_idx` (`users_id_users` ASC) VISIBLE,
    INDEX `fk_friendships_users1_idx` (`users_id_users1` ASC) VISIBLE,
    CONSTRAINT `fk_friendships_users`
    FOREIGN KEY (`users_id_users`)
    REFERENCES `Asignacion_1`.`users` (`id_users`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_friendships_users1`
    FOREIGN KEY (`users_id_users1`)
    REFERENCES `Asignacion_1`.`users` (`id_users`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;